PRAGMA foreign_keys = ON;

CREATE TABLE users (
  username VARCHAR(20) NOT NULL,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  filename VARCHAR(64) NOT NULL,
  password VARCHAR(256) NOT NULL,
  PRIMARY KEY(username)
);

CREATE TABLE pastery (
  pastery_id INTEGER PRIMARY KEY AUTOINCREMENT,
  image VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(256) NOT NULL,
  instagram_link VARCHAR(256)

);


CREATE TABLE likes (
  likeid INTEGER PRIMARY KEY AUTOINCREMENT,
  owner VARCHAR(20) NOT NULL,
  pastery_id INTEGER,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (pastery_id)
    REFERENCES posts(postid)
    ON DELETE CASCADE
);

CREATE TABLE views (
  likeid INTEGER PRIMARY KEY AUTOINCREMENT,
  owner VARCHAR(20) NOT NULL,
  pastery_id INTEGER,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (pastery_id)
    REFERENCES posts(postid)
    ON DELETE CASCADE
);